In [ ]:
import psycopg2
import pandas as pd

conexao = psycopg2.connect(host="kesavan.db.elephantsql.com", database="cjwdogrw", user="cjwdogrw", password="acihzKCpPs16aX1MGNmlYqY1OV--19Q6")
cursor = conexao.cursor()

In [ ]:
cursor.execute("""DROP VIEW cliente_pedido""")

In [ ]:
cursor.execute("""CREATE VIEW cliente_pedido AS
                  SELECT pedido.cod_pedido AS numero_pedido,
                          cliente.nome AS nome_cliente
                  FROM pedido
                  INNER JOIN cliente ON (pedido.fk_cod_cliente = cliente.cod_cliente) """)

In [ ]:
cursor.execute("""SELECT * FROM cliente_pedido""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select1 = pd.DataFrame(data=data,columns = colunas) 

select1

   numero_pedido          nome_cliente
0              1       Moises da Silva
1              2        Camila Volponi
2              3  Mariazinha Feirreira
3              4        Vitor da Silva
4              5    Marcelo da Vitória

In [ ]:
cursor.execute("""DROP VIEW produto_em_pedido""")

In [ ]:
cursor.execute("""CREATE VIEW produto_em_pedido AS
                  SELECT pedido.cod_pedido as numero_pedido,
                        produto.nome as nome_produto
                  FROM pedido
                  INNER JOIN pedido_produto ON (pedido.cod_pedido = pedido_produto.fk_cod_pedido)
                  INNER JOIN produto ON (produto.cod_produto = pedido_produto.fk_cod_produto)
                  ORDER BY pedido.cod_pedido  """)

In [ ]:
cursor.execute("""SELECT * FROM produto_em_pedido""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select2 = pd.DataFrame(data=data,columns = colunas) 

select2

   numero_pedido         nome_produto
0              1  Cento de brigadeiro
1              1    Cento de beijinho
2              2  Cento de brigadeiro
3              3    Cento de beijinho
4              3  Cento de brigadeiro
5              4                Pudim
6              5                Pudim
7              5    Bolo de chocolate

In [ ]:
cursor.execute("""DROP VIEW ingrediente_em_produto""")

In [ ]:
cursor.execute("""CREATE VIEW ingrediente_em_produto AS
                  SELECT 	produto.nome AS nome_produto, 
                      ingrediente.nome AS nome_ingrediente, 
                      tipo_medida.descricao AS tipo_medida
                  FROM produto
                  INNER JOIN produto_ingrediente ON (produto.cod_produto = produto_ingrediente.fk_cod_produto)
                  INNER JOIN ingrediente ON (produto_ingrediente.fk_cod_ingrediente = ingrediente.cod_ingrediente)
                  INNER JOIN tipo_medida ON (ingrediente.fk_cod_tipo_medida = tipo_medida.cod_tipo_medida) """)

In [ ]:
cursor.execute("""SELECT * FROM ingrediente_em_produto""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select3 = pd.DataFrame(data=data,columns = colunas) 

select3

           nome_produto     nome_ingrediente     tipo_medida
0          Bolo de fuba                  Ovo         Unidade
1          Bolo de fuba               Açucar          Xicara
2          Bolo de fuba                 Fubá          Xicara
3          Bolo de fuba     Farinha de trigo  Colher de sopa
4          Bolo de fuba                 Óleo            Copo
5          Bolo de fuba                Leite            Copo
6          Bolo de fuba       Fermento em pó  Colher de sopa
7   Cento de brigadeiro      Leite condesado           Caixa
8   Cento de brigadeiro    Margarina sem sal  Colher de sopa
9   Cento de brigadeiro         Achocolatado  Colher de sopa
10  Cento de brigadeiro  Chocolate granulado         A gosto

In [ ]:
cursor.execute("""DROP VIEW preparo_em_produto""")

In [ ]:
cursor.execute("""CREATE VIEW preparo_em_produto AS
                  SELECT 	produto.nome, 
                      preparo.ordem,
                      preparo.descricao_passo
                  FROM produto
                  INNER JOIN preparo ON (produto.cod_produto = preparo.fk_cod_produto) """)

In [ ]:
cursor.execute("""SELECT * FROM preparo_em_produto""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select4 = pd.DataFrame(data=data,columns = colunas) 

select4

,nome,ordem,descricao_passo
0,Bolo de fuba,1,Bata todos os ingredientes no liquidificador.
1,Bolo de fuba,2,Coloque em uma forma untada e enfarinhada.
2,Bolo de fuba,3,"Leve ao forno preaquecido e deixe assar, por c..."
3,Cento de brigadeiro,1,"Em uma panela funda, acrescente o leite conden..."
4,Cento de brigadeiro,2,Cozinhe em fogo médio e mexa até que o brigade...
5,Cento de brigadeiro,3,Deixe esfriar e faça pequenas bolas com a mão ...

In [ ]:
cursor.execute("""DROP VIEW telefone_em_cliente""")

In [ ]:
cursor.execute("""CREATE VIEW telefone_em_cliente AS
                  SELECT 	cliente.nome AS nome_cliente,
                      telefone.descricao AS numero_telefone
                  FROM cliente
                  INNER JOIN telefone ON (cliente.cod_cliente = telefone.fk_cod_cliente)
                  ORDER BY cliente.nome """)

In [ ]:
cursor.execute("""SELECT * FROM telefone_em_cliente""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select5 = pd.DataFrame(data=data,columns = colunas) 

select5

           nome_cliente numero_telefone
0        Camila Volponi   27 99999-2222
1    Marcelo da Vitória   27 99999-5555
2  Mariazinha Feirreira   27 99999-3333
3       Moises da Silva   27 99999-1111
4       Moises da Silva   21 99555-6515
5       Moises da Silva   21 92565-1447
6        Vitor da Silva   27 99999-4444
7        Vitor da Silva   27 95545-1552

In [ ]:
cursor.execute("""DROP VIEW pedido_pagamento""")

In [ ]:
cursor.execute("""CREATE VIEW pedido_pagamento AS
                  SELECT 	pedido.cod_pedido AS numero_pedido,
                      pedido.data_hora_entrega_prevista,
                      pedido.preco_total AS valor_total_pedido,
                      tipo_pagamento.descricao AS tipo_pagamento
                  FROM pedido
                  INNER JOIN tipo_pagamento ON (tipo_pagamento.cod_tipo_pagamento = pedido.fk_cod_tipo_pagamento)
                  ORDER BY pedido.cod_pedido""")

In [ ]:
cursor.execute("""SELECT * FROM pedido_pagamento""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select6 = pd.DataFrame(data=data,columns = colunas) 

select6

   numero_pedido data_hora_entrega_prevista  valor_total_pedido tipo_pagamento
0              1        2022-05-21 10:11:00               100.0            PIX
1              2        2022-05-22 10:11:00                50.0       Dinheiro
2              3        2022-05-23 10:11:00               150.0        Crédito
3              4        2022-05-24 10:11:00               100.0        Crédito
4              5        2022-05-25 10:11:00                50.0         PicPay

In [38]:
conexao.close();