In [ ]:
cursor.close()

In [ ]:
import psycopg2
import pandas as pd

conexao = psycopg2.connect(host="kesavan.db.elephantsql.com", database="cjwdogrw", user="cjwdogrw", password="acihzKCpPs16aX1MGNmlYqY1OV--19Q6")
cursor = conexao.cursor()

In [ ]:
cursor.execute("""SELECT 	cliente.nome AS nome_cliente, 
                          telefone.descricao AS telefone_cliente, 
                          pedido.preco_total, 
                          pedido.data_hora_entrega_prevista, 
                          tipo_pagamento.descricao AS tipo_pagamento, 
                          produto.nome AS nome_produto, 
                          produto.preco AS preco_produto,
                          pedido_produto.quantidade AS quantidade_produto_no_pedido,
                          preparo.ordem AS ordem_passo,
                          preparo.descricao_passo AS passo,
                          ingrediente.nome AS ingrediente,
                          produto_ingrediente.quantidade AS quantidade_ingredientes,
                          tipo_medida.descricao AS tipo_medida
                  FROM pedido
                  INNER JOIN cliente ON (cliente.cod_cliente = pedido.fk_cod_cliente)
                  INNER JOIN telefone ON (cliente.cod_cliente = telefone.fk_cod_cliente)
                  INNER JOIN tipo_pagamento ON (tipo_pagamento.cod_tipo_pagamento = pedido.fk_cod_tipo_pagamento)
                  INNER JOIN pedido_produto ON (pedido.cod_pedido = pedido_produto.fk_cod_pedido)
                  INNER JOIN produto ON (pedido_produto.fk_cod_produto = produto.cod_produto)
                  INNER JOIN preparo ON (produto.cod_produto = preparo.fk_cod_produto)
                  INNER JOIN produto_ingrediente ON (produto.cod_produto = produto_ingrediente.fk_cod_produto)
                  INNER JOIN ingrediente ON (produto_ingrediente.fk_cod_ingrediente = ingrediente.cod_ingrediente)
                  INNER JOIN tipo_medida ON (ingrediente.fk_cod_tipo_medida = tipo_medida.cod_tipo_medida)
                  WHERE cliente.cod_cliente = 1
                  ORDER BY cliente.nome""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select1 = pd.DataFrame(data=data,columns = colunas) 

select1

,nome_cliente,telefone_cliente,preco_total,data_hora_entrega_prevista,tipo_pagamento,nome_produto,preco_produto,quantidade_produto_no_pedido,ordem_passo,passo,ingrediente,quantidade_ingredientes,tipo_medida
0,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,1,"Em uma panela funda, acrescente o leite conden...",Leite condesado,1,Caixa
1,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,2,Cozinhe em fogo médio e mexa até que o brigade...,Leite condesado,1,Caixa
2,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,3,Deixe esfriar e faça pequenas bolas com a mão ...,Leite condesado,1,Caixa
3,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,1,"Em uma panela funda, acrescente o leite conden...",Margarina sem sal,1,Colher de sopa
4,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,2,Cozinhe em fogo médio e mexa até que o brigade...,Margarina sem sal,1,Colher de sopa
5,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,3,Deixe esfriar e faça pequenas bolas com a mão ...,Margarina sem sal,1,Colher de sopa
6,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,1,"Em uma panela funda, acrescente o leite conden...",Achocolatado,7,Colher de sopa
7,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,2,Cozinhe em fogo médio e mexa até que o brigade...,Achocolatado,7,Colher de sopa
8,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,3,Deixe esfriar e faça pequenas bolas com a mão ...,Achocolatado,7,Colher de sopa
9,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,1,"Em uma panela funda, acrescente o leite conden...",Chocolate granulado,1,A gosto
10,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,2,Cozinhe em fogo médio e mexa até que o brigade...,Chocolate granulado,1,A gosto
11,Moises da Silva,27 99999-1111,100.0,2022-05-21 10:11:00,PIX,Cento de brigadeiro,50.0,1,3,Deixe esfriar e faça pequenas bolas com a mão ...,Chocolate granulado,1,A gosto

In [ ]:
cursor.execute("""SELECT  produto.nome as nome_produto,
                          ingrediente.nome as nome_ingrediente,
                          produto_ingrediente.quantidade AS quantidade_ingrediente,
                          tipo_medida.descricao as tipo_medida
                  FROM produto
                  INNER JOIN produto_ingrediente ON (produto.cod_produto = produto_ingrediente.fk_cod_produto)
                  INNER JOIN ingrediente ON (produto_ingrediente.fk_cod_ingrediente = ingrediente.cod_ingrediente)
                  INNER JOIN tipo_medida ON (ingrediente.fk_cod_tipo_medida = tipo_medida.cod_tipo_medida)
                  ORDER BY produto.nome """)

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select2 = pd.DataFrame(data=data,columns = colunas) 

select2

,nome_produto,nome_ingrediente,quantidade_ingrediente,tipo_medida
0,Bolo de fuba,Ovo,3,Unidade
1,Bolo de fuba,Açucar,2,Xicara
2,Bolo de fuba,Fubá,2,Xicara
3,Bolo de fuba,Farinha de trigo,3,Colher de sopa
4,Bolo de fuba,Óleo,1,Copo
5,Bolo de fuba,Leite,1,Copo
6,Bolo de fuba,Fermento em pó,1,Colher de sopa
7,Cento de brigadeiro,Leite condesado,1,Caixa
8,Cento de brigadeiro,Margarina sem sal,1,Colher de sopa
9,Cento de brigadeiro,Achocolatado,7,Colher de sopa
10,Cento de brigadeiro,Chocolate granulado,1,A gosto

In [ ]:
cursor.execute("""SELECT  produto.nome as nome_produto,
                          preparo.ordem,
                          preparo.descricao_passo as passo
                  FROM produto
                  INNER JOIN preparo ON (produto.cod_produto = preparo.fk_cod_produto)
                  ORDER BY produto.nome,ordem """)

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select3 = pd.DataFrame(data=data,columns = colunas) 

select3

,nome_produto,ordem,passo
0,Bolo de fuba,1,Bata todos os ingredientes no liquidificador.
1,Bolo de fuba,2,Coloque em uma forma untada e enfarinhada.
2,Bolo de fuba,3,"Leve ao forno preaquecido e deixe assar, por c..."
3,Cento de brigadeiro,1,"Em uma panela funda, acrescente o leite conden..."
4,Cento de brigadeiro,2,Cozinhe em fogo médio e mexa até que o brigade...
5,Cento de brigadeiro,3,Deixe esfriar e faça pequenas bolas com a mão ...

In [ ]:
cursor.execute("""SELECT  cliente.nome as nome_cliente,
                          telefone.descricao as telefone,
                          produto.nome as produto,
                          pedido.data_hora_entrega_prevista,
                          pedido.preco_total as valor_total_pedido,
                          tipo_pagamento.descricao as tipo_pagamento
                  FROM pedido
                  INNER JOIN cliente ON (pedido.fk_cod_cliente = cliente.cod_cliente)
                  INNER JOIN telefone ON (cliente.cod_cliente = telefone.fk_cod_cliente)
                  INNER JOIN tipo_pagamento ON (tipo_pagamento.cod_tipo_pagamento = pedido.fk_cod_tipo_pagamento)
                  INNER JOIN pedido_produto ON (pedido.cod_pedido = pedido_produto.fk_cod_pedido)
                  INNER JOIN produto ON (produto.cod_produto = pedido_produto.fk_cod_produto)
                  ORDER BY cliente.nome """)

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select4 = pd.DataFrame(data=data,columns = colunas) 

select4

,nome_cliente,telefone,produto,data_hora_entrega_prevista,valor_total_pedido,tipo_pagamento
0,Camila Volponi,27 99999-2222,Cento de brigadeiro,2022-05-22 10:11:00,50.0,Dinheiro
1,Marcelo da Vitória,27 99999-5555,Pudim,2022-05-25 10:11:00,50.0,PicPay
2,Marcelo da Vitória,27 99999-5555,Bolo de chocolate,2022-05-25 10:11:00,50.0,PicPay
3,Mariazinha Feirreira,27 99999-3333,Cento de beijinho,2022-05-23 10:11:00,150.0,Crédito
4,Mariazinha Feirreira,27 99999-3333,Cento de brigadeiro,2022-05-23 10:11:00,150.0,Crédito
5,Moises da Silva,27 99999-1111,Cento de brigadeiro,2022-05-21 10:11:00,100.0,PIX
6,Moises da Silva,27 99999-1111,Cento de beijinho,2022-05-21 10:11:00,100.0,PIX
7,Vitor da Silva,27 99999-4444,Pudim,2022-05-24 10:11:00,100.0,Crédito

In [ ]:
cursor.execute("""SELECT  cliente.nome as nome_cliente,
                          telefone.descricao as numero_telefone
                  FROM cliente
                  INNER JOIN telefone ON (telefone.fk_cod_cliente = cliente.cod_cliente)
                  ORDER BY cliente.nome """)

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select5 = pd.DataFrame(data=data,columns = colunas) 

select5

           nome_cliente numero_telefone
0        Camila Volponi   27 99999-2222
1    Marcelo da Vitória   27 99999-5555
2  Mariazinha Feirreira   27 99999-3333
3       Moises da Silva   27 99999-1111
4        Vitor da Silva   27 99999-4444

In [ ]:
cursor.execute("""SELECT  cliente.nome as nome_cliente,
                          pedido.cod_pedido as numero_pedido,
                          produto.nome as nome_produto
                  FROM cliente
                  INNER JOIN pedido ON (pedido.fk_cod_cliente = cliente.cod_cliente)
                  INNER JOIN pedido_produto ON (pedido.cod_pedido = pedido_produto.fk_cod_pedido)
                  INNER JOIN produto ON (produto.cod_produto = pedido_produto.fk_cod_produto)
                  ORDER BY cliente.nome """)

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select6 = pd.DataFrame(data=data,columns = colunas) 

select6

           nome_cliente  numero_pedido         nome_produto
0        Camila Volponi              2  Cento de brigadeiro
1    Marcelo da Vitória              5                Pudim
2    Marcelo da Vitória              5    Bolo de chocolate
3  Mariazinha Feirreira              3    Cento de beijinho
4  Mariazinha Feirreira              3  Cento de brigadeiro
5       Moises da Silva              1  Cento de brigadeiro
6       Moises da Silva              1    Cento de beijinho
7        Vitor da Silva              4                Pudim

In [27]:
conexao.close()