In [ ]:
import psycopg2
import pandas as pd

conexao = psycopg2.connect(host="kesavan.db.elephantsql.com", database="cjwdogrw", user="cjwdogrw", password="acihzKCpPs16aX1MGNmlYqY1OV--19Q6")
cursor = conexao.cursor()

In [ ]:
cursor.execute("""select cliente.nome as nome_cliente,pedido.cod_pedido from cliente
                  left join pedido on (cliente.cod_cliente = pedido.fk_cod_cliente)""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select1 = pd.DataFrame(data=data,columns = colunas) 

select1

           nome_cliente  cod_pedido
0       Moises da Silva         1.0
1        Camila Volponi         2.0
2  Mariazinha Feirreira         3.0
3        Vitor da Silva         4.0
4    Marcelo da Vitória         5.0
5       Gustavo Ferrari         NaN
6          Clara Santos         NaN
7           Higor Silva         NaN

In [ ]:
cursor.execute("""select produto.nome as nome_produto, pedido_produto.fk_cod_pedido as pedido from pedido_produto
                  right join produto on (produto.cod_produto = pedido_produto.fk_cod_pedido)
                  order by pedido; """)

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select2 = pd.DataFrame(data=data,columns = colunas) 

select2

          nome_produto  pedido
0  Cento de brigadeiro       1
1  Cento de brigadeiro       1
2         Bolo de fuba       2
3    Cento de beijinho       3
4    Cento de beijinho       3
5    Bolo de chocolate       4
6                Pudim       5
7                Pudim       5

In [ ]:
cursor.execute("""select cliente.nome, telefone.descricao, pedido.cod_pedido from cliente 
                  full join telefone on (cliente.cod_cliente = telefone.fk_cod_cliente)
                  full join pedido on (cliente.cod_cliente = pedido.fk_cod_cliente)""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select3 = pd.DataFrame(data=data,columns = colunas) 

select3

                    nome      descricao  cod_pedido
0        Moises da Silva  21 92565-1447         1.0
1        Moises da Silva  21 99555-6515         1.0
2        Moises da Silva  27 99999-1111         1.0
3         Camila Volponi  27 99999-2222         2.0
4   Mariazinha Feirreira  27 99999-3333         3.0
5         Vitor da Silva  27 95545-1552         4.0
6         Vitor da Silva  27 99999-4444         4.0
7     Marcelo da Vitória  27 99999-5555         5.0
8        Gustavo Ferrari           None         NaN
9           Clara Santos           None         NaN
10           Higor Silva           None         NaN

In [ ]:
cursor.execute(""" select produto.nome, preparo.descricao_passo from produto 
                   left join preparo on (produto.cod_produto = preparo.fk_cod_produto)""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select4 = pd.DataFrame(data=data,columns = colunas) 

select4

                  nome                                    descricao_passo
0         Bolo de fuba      Bata todos os ingredientes no liquidificador.
1         Bolo de fuba         Coloque em uma forma untada e enfarinhada.
2         Bolo de fuba  Leve ao forno preaquecido e deixe assar, por c...
3  Cento de brigadeiro  Em uma panela funda, acrescente o leite conden...
4  Cento de brigadeiro  Cozinhe em fogo médio e mexa até que o brigade...
5  Cento de brigadeiro  Deixe esfriar e faça pequenas bolas com a mão ...
6                Pudim                                               None
7    Bolo de chocolate                                               None
8    Cento de beijinho                                               None

In [ ]:
conexao.close()