In [ ]:
import psycopg2
import pandas as pd

conexao = psycopg2.connect(host="kesavan.db.elephantsql.com", database="cjwdogrw", user="cjwdogrw", password="acihzKCpPs16aX1MGNmlYqY1OV--19Q6")
cursor = conexao.cursor()

In [ ]:
cursor.execute("""SELECT 	fk_cod_pedido AS numero_pedido, 
                          SUM(quantidade*preco) AS valor_total_pedido
                  FROM pedido_produto
                  GROUP BY fk_cod_pedido
                  ORDER BY fk_cod_pedido """)

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select1 = pd.DataFrame(data=data,columns = colunas) 

select1

   numero_pedido  valor_total_pedido
0              1               100.0
1              2                50.0
2              3               150.0
3              4               100.0
4              5                50.0

In [ ]:
cursor.execute("""SELECT COUNT(cod_cliente) AS quantidade_cliente_no_sistema
                  FROM cliente """)

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select2 = pd.DataFrame(data=data,columns = colunas) 

select2

   quantidade_cliente_no_sistema
0                              5

In [ ]:
cursor.execute("""SELECT 	tipo_pagamento.descricao as tipo_pagamento,
                          COUNT(pedido.fk_cod_tipo_pagamento) AS quantidade_utilizada_forma_pagamento
                  FROM pedido
                  INNER JOIN tipo_pagamento ON (tipo_pagamento.cod_tipo_pagamento = pedido.fk_cod_tipo_pagamento)
                  GROUP BY tipo_pagamento.descricao""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select3 = pd.DataFrame(data=data,columns = colunas) 

select3

  tipo_pagamento  quantidade_utilizada_forma_pagamento
0        Crédito                                     2
1            PIX                                     1
2         PicPay                                     1
3       Dinheiro                                     1

In [ ]:
cursor.execute("""SELECT 	produto.nome AS nome_produto,
                          COUNT(produto_ingrediente.fk_cod_ingrediente) AS quantidade_ingredientes_no_produto
                  FROM produto
                  INNER JOIN produto_ingrediente ON (produto.cod_produto = produto_ingrediente.fk_cod_produto)
                  GROUP BY produto.nome
                  ORDER BY produto.nome""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select4 = pd.DataFrame(data=data,columns = colunas) 

select4

          nome_produto  quantidade_ingredientes_no_produto
0         Bolo de fuba                                   7
1  Cento de brigadeiro                                   4

In [ ]:
cursor.execute("""SELECT AVG(preco_total) AS media_preco_pedidos FROM pedido""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select5 = pd.DataFrame(data=data,columns = colunas) 

select5

   media_preco_pedidos
0                 90.0

In [ ]:
cursor.execute("""SELECT 	pedido.cod_pedido AS numero_pedido,
                      cliente.nome AS nome_cliente,
                      COUNT(pedido_produto.fk_cod_produto) AS quantidade_produto_no_pedido
                  FROM pedido
                  INNER JOIN cliente ON (pedido.fk_cod_cliente = cliente.cod_cliente)
                  INNER JOIN pedido_produto ON (pedido.cod_pedido = pedido_produto.fk_cod_pedido)
                  GROUP BY pedido.cod_pedido, cliente.nome
                  ORDER BY pedido.cod_pedido 	""")

data = cursor.fetchall()

colunas = []

for col in cursor.description:
  colunas.append(col[0])

select6 = pd.DataFrame(data=data,columns = colunas) 

select6

   numero_pedido          nome_cliente  quantidade_produto_no_pedido
0              1       Moises da Silva                             2
1              2        Camila Volponi                             1
2              3  Mariazinha Feirreira                             2
3              4        Vitor da Silva                             1
4              5    Marcelo da Vitória                             2

In [ ]:
conexao.close()